/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\ctrl\cc2640_hci_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\ctrl\cc2640_ll_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_att_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_gap_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_gatt_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_l2cap_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_profiles_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_smp_pxxx.a"
"D:\BLE\test\smallest\GUA_CC2640R2F_SDK\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_sm_pxxx.a"
